#ifndef HOMEEDGE_CONFIG_H
#define HOMEEDGE_CONFIG_H

#define HOMEEDGE_DEVICE_ID "homeedge_dev"
#define HOMEEDGE_DEVICE_NAME "HomeEdge Dev"

#define HOMEEDGE_MANUFACTURER "HomeEdge"
#define HOMEEDGE_MODEL "ESP32-S3 Environmental Monitor"

#define HOMEEDGE_FIRMWARE_VERSION "0.1.0"

#define HOMEEDGE_TOPIC_PREFIX "homeedge/dev"

#define HOMEEDGE_TOPIC_TEMPERATURE HOMEEDGE_TOPIC_PREFIX "/temperature_f"
#define HOMEEDGE_TOPIC_HUMIDITY    HOMEEDGE_TOPIC_PREFIX "/humidity"
#define HOMEEDGE_TOPIC_STATUS      HOMEEDGE_TOPIC_PREFIX "/status"
#define HOMEEDGE_TOPIC_RSSI        HOMEEDGE_TOPIC_PREFIX "/rssi"
#define HOMEEDGE_TOPIC_UPTIME      HOMEEDGE_TOPIC_PREFIX "/uptime"
#define HOMEEDGE_TOPIC_FIRMWARE    HOMEEDGE_TOPIC_PREFIX "/firmware"

#define HOMEEDGE_UNIQUE_ID_TEMPERATURE HOMEEDGE_DEVICE_ID "_temperature"
#define HOMEEDGE_UNIQUE_ID_HUMIDITY    HOMEEDGE_DEVICE_ID "_humidity"
#define HOMEEDGE_UNIQUE_ID_RSSI        HOMEEDGE_DEVICE_ID "_rssi"
#define HOMEEDGE_UNIQUE_ID_UPTIME      HOMEEDGE_DEVICE_ID "_uptime"
#define HOMEEDGE_UNIQUE_ID_FIRMWARE    HOMEEDGE_DEVICE_ID "_firmware"

#define HOMEEDGE_DISCOVERY_PREFIX "homeassistant/sensor/"

#define HOMEEDGE_DISCOVERY_TOPIC_TEMPERATURE HOMEEDGE_DISCOVERY_PREFIX HOMEEDGE_UNIQUE_ID_TEMPERATURE "/config"
#define HOMEEDGE_DISCOVERY_TOPIC_HUMIDITY    HOMEEDGE_DISCOVERY_PREFIX HOMEEDGE_UNIQUE_ID_HUMIDITY "/config"
#define HOMEEDGE_DISCOVERY_TOPIC_RSSI        HOMEEDGE_DISCOVERY_PREFIX HOMEEDGE_UNIQUE_ID_RSSI "/config"
#define HOMEEDGE_DISCOVERY_TOPIC_UPTIME      HOMEEDGE_DISCOVERY_PREFIX HOMEEDGE_UNIQUE_ID_UPTIME "/config"
#define HOMEEDGE_DISCOVERY_TOPIC_FIRMWARE    HOMEEDGE_DISCOVERY_PREFIX HOMEEDGE_UNIQUE_ID_FIRMWARE "/config"

#define HOMEEDGE_TELEMETRY_INTERVAL_MS 5000

#endif