#ifndef HOMEEDGE_CONFIG_H
#define HOMEEDGE_CONFIG_H
#define HOMEEDGE_PROFILE_DEV      1
#define HOMEEDGE_PROFILE_OFFICE   2
#define HOMEEDGE_PROFILE_LAUNDRY  3
#define HOMEEDGE_PROFILE_GARAGE   4

#define HOMEEDGE_ACTIVE_PROFILE HOMEEDGE_PROFILE_DEV

#if HOMEEDGE_ACTIVE_PROFILE == HOMEEDGE_PROFILE_DEV

#define HOMEEDGE_DEVICE_ID "homeedge_dev"
#define HOMEEDGE_DEVICE_NAME "HomeEdge Dev"
#define HOMEEDGE_TOPIC_PREFIX "homeedge/dev"
#define HOMEEDGE_TELEMETRY_INTERVAL_MS 5000U
#define HOMEEDGE_HAS_ENV_SENSOR 1
#define HOMEEDGE_HAS_WASHER_MONITOR 0
#define HOMEEDGE_HAS_FREEZER_MONITOR 0

#elif HOMEEDGE_ACTIVE_PROFILE == HOMEEDGE_PROFILE_OFFICE

#define HOMEEDGE_DEVICE_ID "homeedge_office"
#define HOMEEDGE_DEVICE_NAME "HomeEdge Office"
#define HOMEEDGE_TOPIC_PREFIX "homeedge/office"
#define HOMEEDGE_TELEMETRY_INTERVAL_MS 900000U
#define HOMEEDGE_HAS_ENV_SENSOR 1
#define HOMEEDGE_HAS_WASHER_MONITOR 0
#define HOMEEDGE_HAS_FREEZER_MONITOR 0

#elif HOMEEDGE_ACTIVE_PROFILE == HOMEEDGE_PROFILE_LAUNDRY

#define HOMEEDGE_DEVICE_ID "homeedge_laundry"
#define HOMEEDGE_DEVICE_NAME "HomeEdge Laundry"
#define HOMEEDGE_TOPIC_PREFIX "homeedge/laundry"
#define HOMEEDGE_TELEMETRY_INTERVAL_MS 900000U

#define HOMEEDGE_HAS_ENV_SENSOR 1
#define HOMEEDGE_HAS_WASHER_MONITOR 1
#define HOMEEDGE_HAS_FREEZER_MONITOR 0

#elif HOMEEDGE_ACTIVE_PROFILE == HOMEEDGE_PROFILE_GARAGE

#define HOMEEDGE_DEVICE_ID "homeedge_garage"
#define HOMEEDGE_DEVICE_NAME "HomeEdge Garage"
#define HOMEEDGE_TOPIC_PREFIX "homeedge/garage"
#define HOMEEDGE_TELEMETRY_INTERVAL_MS 900000U

#define HOMEEDGE_HAS_ENV_SENSOR 1
#define HOMEEDGE_HAS_WASHER_MONITOR 0
#define HOMEEDGE_HAS_FREEZER_MONITOR 1

#else

#error "Invalid HOMEEDGE_ACTIVE_PROFILE selected"

#endif

#define HOMEEDGE_MANUFACTURER "HomeEdge"
#define HOMEEDGE_MODEL "ESP32-S3 Environmental Monitor"

#define HOMEEDGE_TOPIC_TEMPERATURE HOMEEDGE_TOPIC_PREFIX "/temperature_f"
#define HOMEEDGE_TOPIC_HUMIDITY    HOMEEDGE_TOPIC_PREFIX "/humidity"
#define HOMEEDGE_TOPIC_STATUS      HOMEEDGE_TOPIC_PREFIX "/status"
#define HOMEEDGE_TOPIC_RSSI        HOMEEDGE_TOPIC_PREFIX "/rssi"
#define HOMEEDGE_TOPIC_UPTIME      HOMEEDGE_TOPIC_PREFIX "/uptime"
#define HOMEEDGE_TOPIC_FIRMWARE    HOMEEDGE_TOPIC_PREFIX "/firmware"
#define HOMEEDGE_TOPIC_FREE_HEAP     HOMEEDGE_TOPIC_PREFIX "/free_heap"
#define HOMEEDGE_TOPIC_MIN_FREE_HEAP HOMEEDGE_TOPIC_PREFIX "/min_free_heap"
#define HOMEEDGE_TOPIC_WIFI_RECONNECTS HOMEEDGE_TOPIC_PREFIX "/wifi_reconnects"
#define HOMEEDGE_TOPIC_MQTT_RECONNECTS HOMEEDGE_TOPIC_PREFIX "/mqtt_reconnects"
#define HOMEEDGE_TOPIC_RESET_REASON HOMEEDGE_TOPIC_PREFIX "/reset_reason"

#define HOMEEDGE_TOPIC_OTA_COMMAND \
    HOMEEDGE_TOPIC_PREFIX "/command/ota"

#define HOMEEDGE_TOPIC_OTA_STATUS \
    HOMEEDGE_TOPIC_PREFIX "/ota/status"

#define HOMEEDGE_OTA_URL \
    "http://192.168.4.30:8088/" HOMEEDGE_TOPIC_PREFIX "/firmware.bin"

#define HOMEEDGE_UNIQUE_ID_TEMPERATURE HOMEEDGE_DEVICE_ID "_temperature"
#define HOMEEDGE_UNIQUE_ID_HUMIDITY    HOMEEDGE_DEVICE_ID "_humidity"
#define HOMEEDGE_UNIQUE_ID_RSSI        HOMEEDGE_DEVICE_ID "_rssi"
#define HOMEEDGE_UNIQUE_ID_UPTIME      HOMEEDGE_DEVICE_ID "_uptime"
#define HOMEEDGE_UNIQUE_ID_FIRMWARE    HOMEEDGE_DEVICE_ID "_firmware"
#define HOMEEDGE_UNIQUE_ID_FREE_HEAP     HOMEEDGE_DEVICE_ID "_free_heap"
#define HOMEEDGE_UNIQUE_ID_MIN_FREE_HEAP HOMEEDGE_DEVICE_ID "_min_free_heap"
#define HOMEEDGE_UNIQUE_ID_WIFI_RECONNECTS HOMEEDGE_DEVICE_ID "_wifi_reconnects"
#define HOMEEDGE_UNIQUE_ID_MQTT_RECONNECTS HOMEEDGE_DEVICE_ID "_mqtt_reconnects"
#define HOMEEDGE_UNIQUE_ID_RESET_REASON HOMEEDGE_DEVICE_ID "_reset_reason"

#define HOMEEDGE_DISCOVERY_PREFIX "homeassistant/sensor/"

#define HOMEEDGE_DISCOVERY_TOPIC_TEMPERATURE HOMEEDGE_DISCOVERY_PREFIX HOMEEDGE_UNIQUE_ID_TEMPERATURE "/config"
#define HOMEEDGE_DISCOVERY_TOPIC_HUMIDITY    HOMEEDGE_DISCOVERY_PREFIX HOMEEDGE_UNIQUE_ID_HUMIDITY "/config"
#define HOMEEDGE_DISCOVERY_TOPIC_RSSI        HOMEEDGE_DISCOVERY_PREFIX HOMEEDGE_UNIQUE_ID_RSSI "/config"
#define HOMEEDGE_DISCOVERY_TOPIC_UPTIME      HOMEEDGE_DISCOVERY_PREFIX HOMEEDGE_UNIQUE_ID_UPTIME "/config"
#define HOMEEDGE_DISCOVERY_TOPIC_FIRMWARE    HOMEEDGE_DISCOVERY_PREFIX HOMEEDGE_UNIQUE_ID_FIRMWARE "/config"
#define HOMEEDGE_DISCOVERY_TOPIC_FREE_HEAP \
    HOMEEDGE_DISCOVERY_PREFIX HOMEEDGE_UNIQUE_ID_FREE_HEAP "/config"

#define HOMEEDGE_DISCOVERY_TOPIC_MIN_FREE_HEAP \
    HOMEEDGE_DISCOVERY_PREFIX HOMEEDGE_UNIQUE_ID_MIN_FREE_HEAP "/config"

#define HOMEEDGE_DISCOVERY_TOPIC_WIFI_RECONNECTS \
    HOMEEDGE_DISCOVERY_PREFIX HOMEEDGE_UNIQUE_ID_WIFI_RECONNECTS "/config"

#define HOMEEDGE_DISCOVERY_TOPIC_MQTT_RECONNECTS \
    HOMEEDGE_DISCOVERY_PREFIX HOMEEDGE_UNIQUE_ID_MQTT_RECONNECTS "/config"

#define HOMEEDGE_DISCOVERY_TOPIC_RESET_REASON \
    HOMEEDGE_DISCOVERY_PREFIX HOMEEDGE_UNIQUE_ID_RESET_REASON "/config"

#endif